"""
Django settings for project production.



this is conviguration for init

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
ENV = os.environ.get('DJANGO_ENV', 'local')


if ENV == 'staging':
    from .staging import *
elif ENV == 'production':
    from .production import *
elif ENV == 'dev':
    from .dev import *
elif ENV == 'local':
    from .local import *
elif ENV == 'playground':
    from .playground import *
else:
    from .local import *

os.environ["DJANGO_ENV"] = ENV