"""
Django settings for project staging.



Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
from .base import *
import os

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'api_gateway',
        'USER': 'postgres',
        'PASSWORD': 'qazwer123',
        'HOST': '34.101.83.119',
        'PORT': '5432',
    }
}




DEBUG = True

ASSET_ROOT = os.path.join(os.path.dirname(BASE_DIR), "project/assets")

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'TIMEOUT': None,
        'LOCATION': [
            'localhost:11211'
        ]
    }
}

REDIS_HOST = '10.30.225.102'
REDIS_PASSWORD = 'E9Pdcux6oYpp'

# REDIS_HOST = 'localhost'
# REDIS_PASSWORD = None

PORT = 7051

ENV = 'dev'

# CONNECTION = psycopg2.connect(host= DATABASES["default"]['HOST'], database=DATABASES["default"]['NAME'], \
#     user=DATABASES["default"]['USER'], password=DATABASES["default"]['PASSWORD'])
# CURS = CONNECTION.cursor()


BROKER_KAFKA = '10.30.225.102:9092'
TOPIC_KAFKA = ["API_GATEWAY_LOG"]


CONFLUENT_KAFKA_CONSUMER = {"bootstrap.servers": BROKER_KAFKA,\
                            "group.id": "apigwlistener",\
                            "enable.auto.commit": True,\
                            "session.timeout.ms": 6000,\
                            "default.topic.config": {"auto.offset.reset": "smallest"}\
                            }

INDEX_NAME = 'apigw_log'


print("DEV")
print("setting succesfully loaded")

