"""
Django settings for project staging.



Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
from .base import *
import os

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME', ''),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}

DEBUG = True

ASSET_ROOT = os.path.join(os.path.dirname(BASE_DIR), "project/assets")

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'TIMEOUT': None,
        'LOCATION': [
            'localhost:11211'
        ]
    }
}

REDIS_HOST = os.environ.get('REDIS_HOST', '')
REDIS_PASSWORD = None

PORT = 7051

ENV = 'staging'

WEBVIEW_AUTH = HTTPBasicAuth(
    'webview',
    'qazwer123'
)

# options = {
#     'statsd_host': 'dogstatsd.datadog-system.svc.cluster.local',
#     'statsd_port': 8125
# }
# initialize(**options)

BROKER_KAFKA = '10.30.225.102:9092'
TOPIC_KAFKA = "API_GATEWAY_LOG"


CONFLUENT_KAFKA_PRODUCER = {"bootstrap.servers": BROKER_KAFKA,
                            "retries": "5"}
KAFKA_PRODUCER = Producer(CONFLUENT_KAFKA_PRODUCER)
print(ENV)
