# Generated by Django 3.1.8 on 2021-04-21 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=96, unique=True, verbose_name='token')),
                ('expiration_datetime', models.BigIntegerField(verbose_name='expiration_epoch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_tokens',
                'db_table': 'user_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSecretKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=256, verbose_name='Secret Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('private_key_host', models.TextField(blank=True, max_length=4596, null=True, verbose_name='private_key_host')),
                ('public_key_host', models.TextField(blank=True, max_length=4596, null=True, verbose_name='public_key_host')),
                ('public_key_partner', models.TextField(blank=True, max_length=4596, null=True, verbose_name='public_key_partner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_key_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user'], name='user_token_user_id_209416_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token'], name='user_token_token_deff65_idx'),
        ),
    ]
