# Generated by Django 3.1.8 on 2021-05-04 14:56

import apigateway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='secretkey',
            field=models.CharField(default=apigateway.models.Consumer.generate_secret, max_length=64),
        ),
        migrations.AlterField(
            model_name='api',
            name='plugin',
            field=models.IntegerField(choices=[(0, 'Passthrough'), (1, 'Basic auth'), (2, 'Key auth'), (3, 'Server auth'), (4, 'HMAC')], default=0),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='apikey',
            field=models.CharField(default=apigateway.models.Consumer.generate_key, max_length=64),
        ),
    ]
