# Generated by Django 3.1.8 on 2021-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0002_auto_20210504_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='secretkey',
            field=models.CharField(default='RyVt80WrrwY5DkGJvJ-fTs0TR8WQ2Lcd4qMDxJD3P9g', max_length=64),
        ),
    ]
