# Generated by Django 3.1.8 on 2021-05-04 15:05

import apigateway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0003_auto_20210504_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='secretkey',
            field=models.CharField(default=apigateway.models.Consumer.generate_secret, max_length=64),
        ),
    ]
