# Generated by Django 3.1.8 on 2021-05-04 15:07

import apigateway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0005_auto_20210504_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='apikey',
            field=models.CharField(default=apigateway.models.Consumer.generate_key, max_length=64),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='secretkey',
            field=models.CharField(default=apigateway.models.Consumer.generate_secret, max_length=256),
        ),
    ]
