# Generated by Django 3.1.8 on 2021-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0006_auto_20210504_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
