# Generated by Django 3.1.8 on 2021-05-20 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apigateway', '0007_auto_20210517_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_api_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Created By API user ID'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Created By user ID'),
        ),
    ]
