# Generated by Django 3.1.8 on 2021-05-20 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apigateway', '0008_auto_20210520_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_by_api_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Modified By API user ID'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_by_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Modified By user ID'),
        ),
    ]
