# Generated by Django 3.1.8 on 2023-08-07 10:36

import apigateway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0009_auto_20210520_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[apigateway.models.alphanumerica_and_space_only]),
        ),
        migrations.AlterField(
            model_name='api',
            name='request_path',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
