# Generated by Django 3.1.8 on 2023-08-08 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apigateway', '0010_auto_20230807_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('service_name', models.CharField(blank=True, max_length=64, null=True)),
                ('response_time', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('MM', models.CharField(blank=True, max_length=64, null=True)),
                ('HH', models.CharField(blank=True, max_length=64, null=True)),
                ('DD', models.CharField(blank=True, max_length=64, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('retry_counter', models.IntegerField(blank=True, null=True)),
                ('inserted_time', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_price_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Created By Price user ID')),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_by_price_user_id', to=settings.AUTH_USER_MODEL, verbose_name='Modified By Price user ID')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.api')),
            ],
        ),
    ]
